# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0016_remove_userprofile_last_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='ip',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, default='', help_text='e.g. Dr., Prof., Sir', max_length=50, verbose_name='Title'),
        ),
    ]
